### ISSUE TITLE
The package home page renders the README.Rmd file instead of the README.md file by default

### ISSUE THREAD

**Issue by const-ae** [grimbough/bioc-code-tools#2]
See for example https://code.bioconductor.org/browse/glmGamPoi/

**Comment by const-ae** [comment]
Okay, so I guess this is a general gitlist problem (see for example https://github.com/klaussilveira/gitlist/pull/852). The relevant code where the README is selected is at https://github.com/klaussilveira/gitlist/blob/master/src/Util/Repository.php#L181

I am not sure if you have forked the gitlist repo because I guess otherwise this will be difficult to fix and I would probably need to file the bug report at https://github.com/klaussilveira/gitlist/issues, correct?

**Comment by grimbough** [comment]
Yes, exactly.  I have got a forked copy of Gitlist, but so far I've shied away from doing anything to the php code (in fact I've so far failed to build it from source and just use the binary!)

It also doesn't look like Gitlist is super active, so maybe trying to patch this myself would be the way to go.  I'll put it on the "would be nice" list.

**Comment by grimbough** [comment]
I've now patched this so the `README.md` file will be rendered preferentially if there are both in the repository.

For reference it's done in https://github.com/grimbough/code.bioconductor.org/blob/main/gitlist/php/Repository.php which is then copied over the original version when the Docker container is created.
